name: IVDA_GROUP
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - jupyterlab
  - ipykernel
  - matplotlib
  - nodejs
  - pip:
    - fastapi
    - uvicorn[standard]
    - python-multipart
